name: Deploy
run-name: Deploy PR ${{ github.event.inputs.apply_pr_number }}

on:
  workflow_dispatch:
    inputs:
      apply_pr_number:
        description: 'The PR Number of terraform apply'
        required: true

jobs:
  terraform_apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - name: Installing prereq packages 
        run: apk add --no-cache curl jq unzip
      - name: Checkout bgr-terraform repository
        uses: actions/checkout@v3
        with:
          repository: BGR-InfraData/bgr-terraform
          token: ${{ secrets.PAT }} # Substitute PAT with your secret containing the Personal Access Token
          fetch-depth: 0
      - name: Install Terraform
        run: |
          TERRAFORM_VERSION=1.3.4
          curl https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip -o terraform_${TERRAFORM_VERSION}_linux_amd64.zip
          unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /usr/local/bin
          terraform -v
      - name: Configure AWS CLI
        run: |
          apk add --no-cache python3 py3-pip
          pip3 install awscli
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Terraform Init and Apply
        run: |
          cd .
          terraform init
          terraform apply -auto-approve